name: "Git Releases"

on:
  push:
    branches:
      - main
      - master
  release:
    types: [released]

jobs:
  deploy-go:
    name: "Deploy Go backend service to ECS"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Determine Environment Name
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            echo "INSTALLATION=production" >> $GITHUB_ENV
          else
            echo "INSTALLATION=shared" >> $GITHUB_ENV
          fi

      - name: Show INSTALLATION
        run: |
          echo "INSTALLATION is set to: $INSTALLATION"

      - name: Show Release Version
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Release tag: ${{ GITHUB_REF_NAME }}"
