name: "Git Releases"

on:
  push:
    branches:
      - main
      - master
  release:
    types: [released]

jobs:
  deploy-go:
    name: "Deploy Go backend service to ECS"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Determine Environment Name
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            echo "INSTALLATION=production" >> $GITHUB_ENV
          else
            echo "INSTALLATION=shared" >> $GITHUB_ENV
          fi

      - name: Show INSTALLATION
        run: |
          echo "INSTALLATION is set to: $INSTALLATION"

      - name: Show Release Version
        if: ${{ github.event_name == 'release' }}
        run: |
          if [[ "${{ github.event.release.tag_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            NAMESPACE=$(echo "${{ github.event.release.tag_name }}" \
              | sed -E 's/-(us|eu)//; s#^v##' \
              | tr '[:upper:]' '[:lower:]' \
              | tr -d ' ' \
              | tr './' '--' \
              | cut -c1-20 \
              | sed 's/-$//')
          fi

          echo "Namespace: $NAMESPACE"
          echo "Release tag: ${{ github.event.release.tag_name }}"

      - name: Checkout a Repo and make a commit 
        run: |
          git config --global user.name "omegazyadav"
          git config --global user.email "omegazyadav1@gmail.com"

          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/coderzplayground/workflow1.git
          cd workflow1
          echo "Update from Repo A at $(date)" > update.txt
          git add update.txt
          git commit -m "Automated commit from Repo A"
          git push origin main

